# Etapa 1: Instalar dependencias
FROM node:20-alpine as dev-deps

WORKDIR /app

COPY package.json package-lock.json* ./


RUN npm install --legacy-peer-deps

# Etapa 2: Construir la aplicación
FROM node:20.19.1 as builder

WORKDIR /app

COPY --from=dev-deps /app/node_modules ./node_modules

COPY . .

RUN npx nx build shell

# Etapa 3: Preparar el entorno de producción
FROM nginx:stable-perl as prod


EXPOSE 80



COPY --from=builder /app/dist/shell /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf

COPY apps/shell/nginx/nginx.conf /etc/nginx/conf.d/default.conf


CMD ["nginx", "-g", "daemon off;"]

